In [118]:
import pandas as pd
import requests

In [119]:
response = requests.get("https://dummyjson.com/recipes")
response

In [120]:
response.status_code

200

In [121]:
response_json = response.json()
type(response_json)

dict

In [122]:
response_json.keys()

dict_keys(['recipes', 'total', 'skip', 'limit'])

In [123]:
type(response_json["recipes"])

list

In [124]:
df = pd.DataFrame(response_json["recipes"])
df = df.drop("id", axis=1)
df.head(3)

,name,ingredients,instructions,prepTimeMinutes,cookTimeMinutes,servings,difficulty,cuisine,caloriesPerServing,tags,userId,image,rating,reviewCount,mealType
0,Classic Margherita Pizza,"[Pizza dough, Tomato sauce, Fresh mozzarella c...","[Preheat the oven to 475°F (245°C)., Roll out ...",20,15,4,Easy,Italian,300,"[Pizza, Italian]",166,https://cdn.dummyjson.com/recipe-images/1.webp,4.6,98,[Dinner]
1,Vegetarian Stir-Fry,"[Tofu, cubed, Broccoli florets, Carrots, slice...","[In a wok, heat sesame oil over medium-high he...",15,20,3,Medium,Asian,250,"[Vegetarian, Stir-fry, Asian]",143,https://cdn.dummyjson.com/recipe-images/2.webp,4.7,26,[Lunch]
2,Chocolate Chip Cookies,"[All-purpose flour, Butter, softened, Brown su...","[Preheat the oven to 350°F (175°C)., In a bowl...",15,10,24,Easy,American,150,"[Cookies, Dessert, Baking]",34,https://cdn.dummyjson.com/recipe-images/3.webp,4.9,13,"[Snack, Dessert]"

In [125]:
df.keys(), len(df.keys())

(Index(['name', 'ingredients', 'instructions', 'prepTimeMinutes',
        'cookTimeMinutes', 'servings', 'difficulty', 'cuisine',
        'caloriesPerServing', 'tags', 'userId', 'image', 'rating',
        'reviewCount', 'mealType'],
       dtype='object'),
 15)

In [126]:
df.dtypes

name                   object
ingredients            object
instructions           object
prepTimeMinutes         int64
cookTimeMinutes         int64
servings                int64
difficulty             object
cuisine                object
caloriesPerServing      int64
tags                   object
userId                  int64
image                  object
rating                float64
reviewCount             int64
mealType               object
dtype: object

In [127]:
df["difficulty"].unique()

array(['Easy', 'Medium'], dtype=object)

In [128]:
df.describe()

,prepTimeMinutes,cookTimeMinutes,servings,caloriesPerServing,userId,rating,reviewCount
count,30.000000,30.000000,30.000000,30.000000,30.000000,30.000000,30.000000
mean,21.500000,19.500000,4.366667,331.333333,107.633333,4.616667,51.633333
std,9.751216,12.821722,3.978245,122.776313,57.135340,0.219848,30.673456
min,5.000000,0.000000,1.000000,120.000000,1.000000,4.200000,0.000000
25%,15.000000,11.250000,3.000000,227.500000,55.750000,4.425000,27.000000
50%,20.000000,20.000000,4.000000,320.000000,129.000000,4.600000,54.000000
75%,30.000000,28.750000,4.000000,415.000000,141.750000,4.775000,81.000000
max,45.000000,45.000000,24.000000,550.000000,207.000000,5.000000,98.000000

In [129]:
type(df.describe())

pandas.core.frame.DataFrame

In [130]:
df.describe().keys()

Index(['prepTimeMinutes', 'cookTimeMinutes', 'servings', 'caloriesPerServing',
       'userId', 'rating', 'reviewCount'],
      dtype='object')

In [131]:
df["cuisine"].unique(), df["cuisine"].nunique()

(array(['Italian', 'Asian', 'American', 'Mexican', 'Mediterranean',
        'Pakistani', 'Japanese', 'Moroccan', 'Korean', 'Greek', 'Thai',
        'Indian', 'Turkish', 'Smoothie', 'Russian', 'Lebanese',
        'Brazilian'], dtype=object),
 17)

In [132]:
recipes_df = df[['name', 'prepTimeMinutes', 'cookTimeMinutes', 'servings', 'caloriesPerServing',
       'userId', 'rating', 'reviewCount']]
recipes_df

,name,prepTimeMinutes,cookTimeMinutes,servings,caloriesPerServing,userId,rating,reviewCount
0,Classic Margherita Pizza,20,15,4,300,166,4.6,98
1,Vegetarian Stir-Fry,15,20,3,250,143,4.7,26
2,Chocolate Chip Cookies,15,10,24,150,34,4.9,13
3,Chicken Alfredo Pasta,15,20,4,500,136,4.9,82
4,Mango Salsa Chicken,15,25,3,380,26,4.9,63
5,Quinoa Salad with Avocado,20,15,4,280,197,4.4,59
6,Tomato Basil Bruschetta,15,10,6,120,137,4.7,95
7,Beef and Broccoli Stir-Fry,20,15,4,380,18,4.7,58
8,Caprese Salad,10,0,2,200,128,4.6,82
9,Shrimp Scampi Pasta,15,20,3,400,114,4.3,5
10,Chicken Biryani,30,45,6,550,133,5.0,32
11,Chicken Karahi,20,30,4,420,49,4.8,68
12,Aloo Keema,25,35,5,380,152,4.6,53
13,Chapli Kebabs,30,20,4,320,152,4.7,98
14,Saag (Spinach) with Makki di Roti,40,30,3,280,43,4.3,86
15,Japanese Ramen Soup,20,25,2,480,85,4.9,38
16,Moroccan Chickpea Tagine,15,30,4,320,207,4.5,50
17,Korean Bibimbap,30,20,2,550,121,4.9,56
18,Greek Moussaka,45,45,6,420,173,4.3,26
19,Butter Chicken (Murgh Makhani),30,25,4,480,138,4.5,44
20,Thai Green Curry,20,30,4,480,153,4.2,18
21,Mango Lassi,10,0,2,180,76,4.7,15
22,Italian Tiramisu,30,0,6,350,130,4.6,0
23,Turkish Kebabs,25,15,4,280,26,4.6,78
24,Blueberry Banana Smoothie,10,0,1,220,16,4.8,30
25,Mexican Street Corn (Elote),15,15,4,180,93,4.6,2
26,Russian Borscht,30,40,6,220,1,4.3,39
27,South Indian Masala Dosa,40,20,4,320,138,4.4,96
28,Lebanese Falafel Wrap,15,10,2,400,110,4.7,84
29,Brazilian Caipirinha,5,0,1,150,134,4.4,55

In [133]:
recipes_df.sort_values('prepTimeMinutes')

,name,prepTimeMinutes,cookTimeMinutes,servings,caloriesPerServing,userId,rating,reviewCount
29,Brazilian Caipirinha,5,0,1,150,134,4.4,55
24,Blueberry Banana Smoothie,10,0,1,220,16,4.8,30
8,Caprese Salad,10,0,2,200,128,4.6,82
21,Mango Lassi,10,0,2,180,76,4.7,15
1,Vegetarian Stir-Fry,15,20,3,250,143,4.7,26
2,Chocolate Chip Cookies,15,10,24,150,34,4.9,13
3,Chicken Alfredo Pasta,15,20,4,500,136,4.9,82
4,Mango Salsa Chicken,15,25,3,380,26,4.9,63
25,Mexican Street Corn (Elote),15,15,4,180,93,4.6,2
6,Tomato Basil Bruschetta,15,10,6,120,137,4.7,95
9,Shrimp Scampi Pasta,15,20,3,400,114,4.3,5
16,Moroccan Chickpea Tagine,15,30,4,320,207,4.5,50
28,Lebanese Falafel Wrap,15,10,2,400,110,4.7,84
20,Thai Green Curry,20,30,4,480,153,4.2,18
15,Japanese Ramen Soup,20,25,2,480,85,4.9,38
0,Classic Margherita Pizza,20,15,4,300,166,4.6,98
11,Chicken Karahi,20,30,4,420,49,4.8,68
7,Beef and Broccoli Stir-Fry,20,15,4,380,18,4.7,58
5,Quinoa Salad with Avocado,20,15,4,280,197,4.4,59
12,Aloo Keema,25,35,5,380,152,4.6,53
23,Turkish Kebabs,25,15,4,280,26,4.6,78
17,Korean Bibimbap,30,20,2,550,121,4.9,56
19,Butter Chicken (Murgh Makhani),30,25,4,480,138,4.5,44
10,Chicken Biryani,30,45,6,550,133,5.0,32
22,Italian Tiramisu,30,0,6,350,130,4.6,0
26,Russian Borscht,30,40,6,220,1,4.3,39
13,Chapli Kebabs,30,20,4,320,152,4.7,98
27,South Indian Masala Dosa,40,20,4,320,138,4.4,96
14,Saag (Spinach) with Makki di Roti,40,30,3,280,43,4.3,86
18,Greek Moussaka,45,45,6,420,173,4.3,26

In [134]:
recipes_df.sort_values(['prepTimeMinutes', 'caloriesPerServing'])

,name,prepTimeMinutes,cookTimeMinutes,servings,caloriesPerServing,userId,rating,reviewCount
29,Brazilian Caipirinha,5,0,1,150,134,4.4,55
21,Mango Lassi,10,0,2,180,76,4.7,15
8,Caprese Salad,10,0,2,200,128,4.6,82
24,Blueberry Banana Smoothie,10,0,1,220,16,4.8,30
6,Tomato Basil Bruschetta,15,10,6,120,137,4.7,95
2,Chocolate Chip Cookies,15,10,24,150,34,4.9,13
25,Mexican Street Corn (Elote),15,15,4,180,93,4.6,2
1,Vegetarian Stir-Fry,15,20,3,250,143,4.7,26
16,Moroccan Chickpea Tagine,15,30,4,320,207,4.5,50
4,Mango Salsa Chicken,15,25,3,380,26,4.9,63
9,Shrimp Scampi Pasta,15,20,3,400,114,4.3,5
28,Lebanese Falafel Wrap,15,10,2,400,110,4.7,84
3,Chicken Alfredo Pasta,15,20,4,500,136,4.9,82
5,Quinoa Salad with Avocado,20,15,4,280,197,4.4,59
0,Classic Margherita Pizza,20,15,4,300,166,4.6,98
7,Beef and Broccoli Stir-Fry,20,15,4,380,18,4.7,58
11,Chicken Karahi,20,30,4,420,49,4.8,68
15,Japanese Ramen Soup,20,25,2,480,85,4.9,38
20,Thai Green Curry,20,30,4,480,153,4.2,18
23,Turkish Kebabs,25,15,4,280,26,4.6,78
12,Aloo Keema,25,35,5,380,152,4.6,53
26,Russian Borscht,30,40,6,220,1,4.3,39
13,Chapli Kebabs,30,20,4,320,152,4.7,98
22,Italian Tiramisu,30,0,6,350,130,4.6,0
19,Butter Chicken (Murgh Makhani),30,25,4,480,138,4.5,44
10,Chicken Biryani,30,45,6,550,133,5.0,32
17,Korean Bibimbap,30,20,2,550,121,4.9,56
14,Saag (Spinach) with Makki di Roti,40,30,3,280,43,4.3,86
27,South Indian Masala Dosa,40,20,4,320,138,4.4,96
18,Greek Moussaka,45,45,6,420,173,4.3,26

In [135]:
recipes_df [   recipes_df["prepTimeMinutes"] < 20 ]

,name,prepTimeMinutes,cookTimeMinutes,servings,caloriesPerServing,userId,rating,reviewCount
1,Vegetarian Stir-Fry,15,20,3,250,143,4.7,26
2,Chocolate Chip Cookies,15,10,24,150,34,4.9,13
3,Chicken Alfredo Pasta,15,20,4,500,136,4.9,82
4,Mango Salsa Chicken,15,25,3,380,26,4.9,63
6,Tomato Basil Bruschetta,15,10,6,120,137,4.7,95
8,Caprese Salad,10,0,2,200,128,4.6,82
9,Shrimp Scampi Pasta,15,20,3,400,114,4.3,5
16,Moroccan Chickpea Tagine,15,30,4,320,207,4.5,50
21,Mango Lassi,10,0,2,180,76,4.7,15
24,Blueberry Banana Smoothie,10,0,1,220,16,4.8,30
25,Mexican Street Corn (Elote),15,15,4,180,93,4.6,2
28,Lebanese Falafel Wrap,15,10,2,400,110,4.7,84
29,Brazilian Caipirinha,5,0,1,150,134,4.4,55

In [136]:
recipes_df [   (recipes_df["prepTimeMinutes"] < 30) &  (recipes_df["prepTimeMinutes"] > 20)  ]

,name,prepTimeMinutes,cookTimeMinutes,servings,caloriesPerServing,userId,rating,reviewCount
12,Aloo Keema,25,35,5,380,152,4.6,53
23,Turkish Kebabs,25,15,4,280,26,4.6,78

In [137]:
recipes_df["difficulty"] = df["difficulty"]
recipes_df

/var/folders/3k/f_77v9pn1r94_xmvm2w3xgqr0000gn/T/ipykernel_6599/3406684217.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  recipes_df["difficulty"] = df["difficulty"]

,name,prepTimeMinutes,cookTimeMinutes,servings,caloriesPerServing,userId,rating,reviewCount,difficulty
0,Classic Margherita Pizza,20,15,4,300,166,4.6,98,Easy
1,Vegetarian Stir-Fry,15,20,3,250,143,4.7,26,Medium
2,Chocolate Chip Cookies,15,10,24,150,34,4.9,13,Easy
3,Chicken Alfredo Pasta,15,20,4,500,136,4.9,82,Medium
4,Mango Salsa Chicken,15,25,3,380,26,4.9,63,Easy
5,Quinoa Salad with Avocado,20,15,4,280,197,4.4,59,Easy
6,Tomato Basil Bruschetta,15,10,6,120,137,4.7,95,Easy
7,Beef and Broccoli Stir-Fry,20,15,4,380,18,4.7,58,Medium
8,Caprese Salad,10,0,2,200,128,4.6,82,Easy
9,Shrimp Scampi Pasta,15,20,3,400,114,4.3,5,Medium
10,Chicken Biryani,30,45,6,550,133,5.0,32,Medium
11,Chicken Karahi,20,30,4,420,49,4.8,68,Easy
12,Aloo Keema,25,35,5,380,152,4.6,53,Medium
13,Chapli Kebabs,30,20,4,320,152,4.7,98,Medium
14,Saag (Spinach) with Makki di Roti,40,30,3,280,43,4.3,86,Medium
15,Japanese Ramen Soup,20,25,2,480,85,4.9,38,Medium
16,Moroccan Chickpea Tagine,15,30,4,320,207,4.5,50,Easy
17,Korean Bibimbap,30,20,2,550,121,4.9,56,Medium
18,Greek Moussaka,45,45,6,420,173,4.3,26,Medium
19,Butter Chicken (Murgh Makhani),30,25,4,480,138,4.5,44,Medium
20,Thai Green Curry,20,30,4,480,153,4.2,18,Medium
21,Mango Lassi,10,0,2,180,76,4.7,15,Easy
22,Italian Tiramisu,30,0,6,350,130,4.6,0,Medium
23,Turkish Kebabs,25,15,4,280,26,4.6,78,Easy
24,Blueberry Banana Smoothie,10,0,1,220,16,4.8,30,Easy
25,Mexican Street Corn (Elote),15,15,4,180,93,4.6,2,Easy
26,Russian Borscht,30,40,6,220,1,4.3,39,Medium
27,South Indian Masala Dosa,40,20,4,320,138,4.4,96,Medium
28,Lebanese Falafel Wrap,15,10,2,400,110,4.7,84,Easy
29,Brazilian Caipirinha,5,0,1,150,134,4.4,55,Easy

In [138]:
recipes_df.describe()

,prepTimeMinutes,cookTimeMinutes,servings,caloriesPerServing,userId,rating,reviewCount
count,30.000000,30.000000,30.000000,30.000000,30.000000,30.000000,30.000000
mean,21.500000,19.500000,4.366667,331.333333,107.633333,4.616667,51.633333
std,9.751216,12.821722,3.978245,122.776313,57.135340,0.219848,30.673456
min,5.000000,0.000000,1.000000,120.000000,1.000000,4.200000,0.000000
25%,15.000000,11.250000,3.000000,227.500000,55.750000,4.425000,27.000000
50%,20.000000,20.000000,4.000000,320.000000,129.000000,4.600000,54.000000
75%,30.000000,28.750000,4.000000,415.000000,141.750000,4.775000,81.000000
max,45.000000,45.000000,24.000000,550.000000,207.000000,5.000000,98.000000

In [139]:
recipes_df["difficulty_convertion"] = df["difficulty"] == "Medium"
recipes_df.head(2)

/var/folders/3k/f_77v9pn1r94_xmvm2w3xgqr0000gn/T/ipykernel_6599/2865729876.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  recipes_df["difficulty_convertion"] = df["difficulty"] == "Medium"

,name,prepTimeMinutes,cookTimeMinutes,servings,caloriesPerServing,userId,rating,reviewCount,difficulty,difficulty_convertion
0,Classic Margherita Pizza,20,15,4,300,166,4.6,98,Easy,False
1,Vegetarian Stir-Fry,15,20,3,250,143,4.7,26,Medium,True

In [140]:
recipes_df["difficulty_convertion"] = df["difficulty"].map({
        "Easy":2, "Medium":5
})
recipes_df.head(2)

/var/folders/3k/f_77v9pn1r94_xmvm2w3xgqr0000gn/T/ipykernel_6599/4258399727.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  recipes_df["difficulty_convertion"] = df["difficulty"].map({

,name,prepTimeMinutes,cookTimeMinutes,servings,caloriesPerServing,userId,rating,reviewCount,difficulty,difficulty_convertion
0,Classic Margherita Pizza,20,15,4,300,166,4.6,98,Easy,2
1,Vegetarian Stir-Fry,15,20,3,250,143,4.7,26,Medium,5

In [141]:
recipes_df.describe()

,prepTimeMinutes,cookTimeMinutes,servings,caloriesPerServing,userId,rating,reviewCount,difficulty_convertion
count,30.000000,30.000000,30.000000,30.000000,30.000000,30.000000,30.000000,30.000000
mean,21.500000,19.500000,4.366667,331.333333,107.633333,4.616667,51.633333,3.600000
std,9.751216,12.821722,3.978245,122.776313,57.135340,0.219848,30.673456,1.522249
min,5.000000,0.000000,1.000000,120.000000,1.000000,4.200000,0.000000,2.000000
25%,15.000000,11.250000,3.000000,227.500000,55.750000,4.425000,27.000000,2.000000
50%,20.000000,20.000000,4.000000,320.000000,129.000000,4.600000,54.000000,5.000000
75%,30.000000,28.750000,4.000000,415.000000,141.750000,4.775000,81.000000,5.000000
max,45.000000,45.000000,24.000000,550.000000,207.000000,5.000000,98.000000,5.000000

In [143]:
from sklearn.preprocessing import LabelEncoder

In [144]:
recipes_df["difficulty_encoded"] = LabelEncoder().fit_transform(recipes_df["difficulty"])
recipes_df.head(2)

/var/folders/3k/f_77v9pn1r94_xmvm2w3xgqr0000gn/T/ipykernel_6599/332748209.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  recipes_df["difficulty_encoded"] = LabelEncoder().fit_transform(recipes_df["difficulty"])

,name,prepTimeMinutes,cookTimeMinutes,servings,caloriesPerServing,userId,rating,reviewCount,difficulty,difficulty_convertion,difficulty_encoded
0,Classic Margherita Pizza,20,15,4,300,166,4.6,98,Easy,2,0
1,Vegetarian Stir-Fry,15,20,3,250,143,4.7,26,Medium,5,1

In [150]:
from sklearn.preprocessing import  MultiLabelBinarizer

In [152]:
MultiLabelBinarizer().fit_transform(df["mealType"])

array([[0, 0, 0, 0, 1, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 1, 0, 0, 0],
       [0, 0, 0, 1, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1, 1, 0, 0, 0],
       [0, 0, 0, 0, 1, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 1, 1, 0, 0],
       [1, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 1, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 1, 0, 0, 0],
       [0, 0, 0, 0, 1, 0, 0, 0, 0],
       [0, 0, 0, 0, 1, 1, 0, 0, 0],
       [0, 0, 0, 0, 1, 1, 0, 0, 0],
       [0, 0, 0, 0, 1, 1, 0, 0, 0],
       [0, 0, 0, 0, 1, 1, 0, 0, 1],
       [0, 0, 1, 0, 1, 1, 0, 0, 0],
       [0, 0, 0, 0, 1, 0, 0, 0, 0],
       [0, 0, 0, 0, 1, 0, 0, 0, 0],
       [0, 0, 0, 0, 1, 0, 0, 0, 0],
       [0, 0, 0, 0, 1, 0, 0, 0, 0],
       [0, 0, 0, 0, 1, 0, 0, 0, 0],
       [0, 0, 0, 0, 1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 1, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 1, 0, 0, 0, 0],
       [0, 1, 1, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 1, 1, 0],
       [0, 0, 0, 0, 1, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 1, 0, 0, 0],
       [0, 1, 0, 0, 0, 0, 0, 0, 0]])

In [169]:
sorted(df["mealType"].explode().unique())
# df.filter(['mealType']).values.flatten()

['Appetizer',
 'Beverage',
 'Breakfast',
 'Dessert',
 'Dinner',
 'Lunch',
 'Side Dish',
 'Snack',
 'Snacks']

In [171]:
meal_types_df  = pd.DataFrame(
    MultiLabelBinarizer().fit_transform(df["mealType"]), columns= sorted(df["mealType"].explode().unique()) )
meal_types_df.head(2)

,Appetizer,Beverage,Breakfast,Dessert,Dinner,Lunch,Side Dish,Snack,Snacks
0,0,0,0,0,1,0,0,0,0
1,0,0,0,0,0,1,0,0,0

In [172]:
meal_types_df["name"] = df["name"]
meal_types_df

,Appetizer,Beverage,Breakfast,Dessert,Dinner,Lunch,Side Dish,Snack,Snacks,name
0,0,0,0,0,1,0,0,0,0,Classic Margherita Pizza
1,0,0,0,0,0,1,0,0,0,Vegetarian Stir-Fry
2,0,0,0,1,0,0,0,1,0,Chocolate Chip Cookies
3,0,0,0,0,1,1,0,0,0,Chicken Alfredo Pasta
4,0,0,0,0,1,0,0,0,0,Mango Salsa Chicken
5,0,0,0,0,0,1,1,0,0,Quinoa Salad with Avocado
6,1,0,0,0,0,0,0,0,0,Tomato Basil Bruschetta
7,0,0,0,0,1,0,0,0,0,Beef and Broccoli Stir-Fry
8,0,0,0,0,0,1,0,0,0,Caprese Salad
9,0,0,0,0,1,0,0,0,0,Shrimp Scampi Pasta
10,0,0,0,0,1,1,0,0,0,Chicken Biryani
11,0,0,0,0,1,1,0,0,0,Chicken Karahi
12,0,0,0,0,1,1,0,0,0,Aloo Keema
13,0,0,0,0,1,1,0,0,1,Chapli Kebabs
14,0,0,1,0,1,1,0,0,0,Saag (Spinach) with Makki di Roti
15,0,0,0,0,1,0,0,0,0,Japanese Ramen Soup
16,0,0,0,0,1,0,0,0,0,Moroccan Chickpea Tagine
17,0,0,0,0,1,0,0,0,0,Korean Bibimbap
18,0,0,0,0,1,0,0,0,0,Greek Moussaka
19,0,0,0,0,1,0,0,0,0,Butter Chicken (Murgh Makhani)
20,0,0,0,0,1,0,0,0,0,Thai Green Curry
21,0,1,0,0,0,0,0,0,0,Mango Lassi
22,0,0,0,1,0,0,0,0,0,Italian Tiramisu
23,0,0,0,0,1,0,0,0,0,Turkish Kebabs
24,0,1,1,0,0,0,0,0,0,Blueberry Banana Smoothie
25,0,0,0,0,0,0,1,1,0,Mexican Street Corn (Elote)
26,0,0,0,0,1,0,0,0,0,Russian Borscht
27,0,0,1,0,0,0,0,0,0,South Indian Masala Dosa
28,0,0,0,0,0,1,0,0,0,Lebanese Falafel Wrap
29,0,1,0,0,0,0,0,0,0,Brazilian Caipirinha